//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbContext : DbContext
    {
        public dbContext()
            : base("name=dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActivity> tActivities { get; set; }
        public virtual DbSet<tDegree> tDegrees { get; set; }
        public virtual DbSet<tFaculty> tFaculties { get; set; }
        public virtual DbSet<tGrade> tGrades { get; set; }
        public virtual DbSet<tGroup> tGroups { get; set; }
        public virtual DbSet<tLoginInfo> tLoginInfoes { get; set; }
        public virtual DbSet<tNorm> tNorms { get; set; }
        public virtual DbSet<tPosition> tPositions { get; set; }
        public virtual DbSet<tProfession> tProfessions { get; set; }
        public virtual DbSet<tPulpit> tPulpits { get; set; }
        public virtual DbSet<tRole> tRoles { get; set; }
        public virtual DbSet<tSemester> tSemesters { get; set; }
        public virtual DbSet<tSubGroup> tSubGroups { get; set; }
        public virtual DbSet<tSubject> tSubjects { get; set; }
        public virtual DbSet<tTitle> tTitles { get; set; }
        public virtual DbSet<tSubjectPrev> tSubjectPrevs { get; set; }
        public virtual DbSet<tDistrib> tDistribs { get; set; }
        public virtual DbSet<tNormPosition> tNormPositions { get; set; }
        public virtual DbSet<tSubjectActivity> tSubjectActivities { get; set; }
        public virtual DbSet<tTeacher> tTeachers { get; set; }
        public virtual DbSet<tSubjectProfession> tSubjectProfessions { get; set; }
        public virtual DbSet<tStream> tStreams { get; set; }
        public virtual DbSet<tSubjectTeacher> tSubjectTeachers { get; set; }
    
        public virtual ObjectResult<GetSubjectActivityList_Result> GetSubjectActivityList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectActivityList_Result>("GetSubjectActivityList");
        }
    
        public virtual ObjectResult<GetSubjectList_Result> GetSubjectList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectList_Result>("GetSubjectList");
        }
    
        public virtual ObjectResult<GetTeacherList_Result> GetTeacherList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeacherList_Result>("GetTeacherList");
        }
    
        public virtual int spLoadSubjectFromWeb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoadSubjectFromWeb");
        }
    
        public virtual ObjectResult<spGetDistribListSubjectOnly_Result> spGetDistribListSubjectOnly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDistribListSubjectOnly_Result>("spGetDistribListSubjectOnly");
        }
    
        public virtual ObjectResult<GetNormPositionList_Result> GetNormPositionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNormPositionList_Result>("GetNormPositionList");
        }
    
        public virtual ObjectResult<GetGroupSubGroupList_Result> GetGroupSubGroupList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGroupSubGroupList_Result>("GetGroupSubGroupList");
        }
    
        public virtual ObjectResult<GetStreamList_Result> GetStreamList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStreamList_Result>("GetStreamList");
        }
    
        public virtual ObjectResult<GetSubjectProfessionList_Result> GetSubjectProfessionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectProfessionList_Result>("GetSubjectProfessionList");
        }
    
        public virtual ObjectResult<GetTeacherSubjectList_Result> GetTeacherSubjectList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeacherSubjectList_Result>("GetTeacherSubjectList");
        }
    
        public virtual int spLoadtSubject1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoadtSubject1");
        }
    
        public virtual ObjectResult<string> CreateHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CreateHistory");
        }
    }
}
