//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGroup()
        {
            this.tSubGroups = new HashSet<tSubGroup>();
            this.tDistribs = new HashSet<tDistrib>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public Nullable<int> GroupAmount { get; set; }
        public Nullable<int> GradeID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<double> GroupPart { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tGrade tGrade { get; set; }
        public virtual tProfession tProfession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSubGroup> tSubGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDistrib> tDistribs { get; set; }
    }
}
