//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLoginInfo
    {
        public int LoginID { get; set; }
        public string UserName { get; set; }
        public byte[] UserPassword { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tRole tRole { get; set; }
    }
}
