//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNormPosition
    {
        public int NormID { get; set; }
        public int PositionID { get; set; }
        public Nullable<int> Hour { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int NormPositionID { get; set; }
    
        public virtual tNorm tNorm { get; set; }
        public virtual tPosition tPosition { get; set; }
    }
}
