//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStream
    {
        public int StreamID { get; set; }
        public string StreamStructure { get; set; }
        public string StreamSubject { get; set; }
        public Nullable<int> PulpitID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ID { get; set; }
    
        public virtual tPulpit tPulpit { get; set; }
        public virtual tSemester tSemester { get; set; }
    }
}
