//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubjectPrev
    {
        public string specName { get; set; }
        public string DisciplineName { get; set; }
        public string ExamSem { get; set; }
        public string CreditSem { get; set; }
        public string TotalHour { get; set; }
        public string AudutoriumHour { get; set; }
        public string LecturesHour { get; set; }
        public string LabHour { get; set; }
        public string PracticHour { get; set; }
        public string SeminarHour { get; set; }
        public string first_gr_first_sem_TotalHour { get; set; }
        public string first_gr_first_sem_AudHour { get; set; }
        public string first_gr_second_sem_TotalHour { get; set; }
        public string first_gr_second_sem_AudHour { get; set; }
        public string second_gr_third_sem_TotalHour { get; set; }
        public string second_gr_third_sem_AudHour { get; set; }
        public string second_gr_fourth_sem_TotalHour { get; set; }
        public string second_gr_fourth_sem_AudHour { get; set; }
        public string third_gr_fifth_sem_TotalHour { get; set; }
        public string third_gr_fifth_sem_AudHour { get; set; }
        public string third_gr_sixth_sem_TotalHour { get; set; }
        public string third_gr_sixth_sem_AudHour { get; set; }
        public string fourth_gr_seventh_sem_TotalHour { get; set; }
        public string fourth_gr_seventh_sem_AudHour { get; set; }
        public string fourth_gr_eighth_sem_TotalHour { get; set; }
        public string fourth_gr_eighth_sem_AudHour { get; set; }
        public bool isDeleted { get; set; }
        public int Id { get; set; }
    }
}
