//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubjectTeacher
    {
        public int SubjectID { get; set; }
        public int TeacherID { get; set; }
        public Nullable<int> StreamID { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int SubjectTeacherID { get; set; }
    
        public virtual tSubject tSubject { get; set; }
        public virtual tTeacher tTeacher { get; set; }
    }
}
